### ISSUE TITLE
English language translation

### ISSUE THREAD

**Issue by Mrsevic** [vicjl/Dell7567-OC#1]
Hello there. I am wondering whether or not I/community could help you in adding the english language translation.

It would be extremely helpful for us abroad. 

Thanks

**Comment by vicjl** [comment]
Sure, and if you have finished translating the English version, please pull request to my repository or upload to this Issue.
Thanks

**Comment by Mrsevic** [comment]
Thanks, unfortunately I do not know Chinese a lot, I would need your assistance/clarification. Is there any way we could communicate in English in some group or in private? Thanks

**Comment by vicjl** [comment]
> Thanks, unfortunately I do not know Chinese a lot, I would need your assistance/clarification. Is there any way we could communicate in English in some group or in private? Thanks

You may try to translate it. My English is not good but if you have some untranslatable words, mark it. I will try my best to help you. We have a QQ group and you can find a group number in readme.md, or you can communicate with me in telegram.https://t.me/vicjl
