### ISSUE TITLE
The headset cannot be used after being plugged in.

### ISSUE THREAD

**Issue by Lesliewxj** [vicjl/Dell7567-OC#10]
Could you please tell me if there is no earphone driver in this one? After I finished the installation, everything else was normal. After the earphone was inserted, there was a sound, but it could not be heard.

**Comment by vicjl** [comment]
“该项目使用ComboJack作为耳麦驱动，需要使用ComboJack_For_Dell7567_Only中的文件安装切换弹窗部分，详细安装说明包含在文件中”

**Comment by Lesliewxj** [comment]
我使用了那个kext文件，但是还是不行，耳机插上去之后还是有沙沙的声音，听不清是什么，也没有弹窗。

**Comment by vicjl** [comment]
使用过release里发的combojack那个安装命令了吗？贴一下执行文件完成的图

**Comment by Lesliewxj** [comment]
我执行了release里发的combojack里面的那个install.command文件，结果是这样的。
<img class="img-fluid img-thumbnail d-block" src="https://leslieblog.oss-cn-beijing.aliyuncs.com/install.png" />

**Comment by Lesliewxj** [comment]
[https://leslieblog.oss-cn-beijing.aliyuncs.com/install.png](url)

**Comment by Lesliewxj** [comment]
我执行了release里发的combojack的那个点击安装的command文件，然后还是不行。执行完成后的图片是这样的：
[](https://leslieblog.oss-cn-beijing.aliyuncs.com/install.png)

**Comment by Lesliewxj** [comment]
我执行了release里发的combojack的那个点击安装的command文件，然后还是不行。执行完成后的图片是这样的：
https://raw.githubusercontent.com/Lesliewxj/lesliewxj-image/master/github-image/inistall.1wyoqvtv7080.png

**Comment by vicjl** [comment]
> 我执行了release里发的combojack的那个点击安装的command文件，然后还是不行。执行完成后的图片是这样的：
> https://raw.githubusercontent.com/Lesliewxj/lesliewxj-image/master/github-image/inistall.1wyoqvtv7080.png

检查是否使用了最新Release版本中的Combojack，使用前是否全部解压缩？图中上面有错误提示

**Comment by Lesliewxj** [comment]
我是使用的Release版本中的Combojack，使用的时候也全部解压缩了，图片中我觉得是执行完成之后的结果了，请问一下正确的运行结果应该是什么样的，能否提供一下你的截图，非常感谢。

**Comment by vicjl** [comment]
> 我是使用的Release版本中的Combojack，使用的时候也全部解压缩了，图片中我觉得是执行完成之后的结果了，请问一下正确的运行结果应该是什么样的，能否提供一下你的截图，非常感谢。

/Library/LaunchDaemons/ com. XPS . ComboJack.plist: No such file or directoryLoad failed: 2: No such file or directory
这个是错误提示，指com.xps.combojack.plist没找到，正常应该是复制完成的

**Comment by vicjl** [comment]
> 我是使用的Release版本中的Combojack，使用的时候也全部解压缩了，图片中我觉得是执行完成之后的结果了，请问一下正确的运行结果应该是什么样的，能否提供一下你的截图，非常感谢。

尝试终端cd到combojack文件夹内运行
1. sudo cp com.XPS.ComboJack.plist /Library/LaunchDaemons/
2. sudo chmod 644 /Library/LaunchDaemons/com.XPS.ComboJack.plist
3. sudo chown root:wheel /Library/LaunchDaemons/com.XPS.ComboJack.plist
4. sudo launchctl load /Library/LaunchDaemons/com.XPS.ComboJack.plist

**Comment by Lesliewxj** [comment]
好的，我试一下看看。

**Comment by Lesliewxj** [comment]
应该是我没有下载对那个文件，我后面有时间再试一下。非常感谢。
