### ISSUE TITLE
Support for macOS Monterey

### ISSUE THREAD

**Issue by mishailovic** [vicjl/Dell7567-OC#11]
Will you update EFI for macOS Monterey or you're dropped the development?

**Comment by vicjl** [comment]
> Will you update EFI for macOS Monterey or you're dropped the development?

最近有点忙，最迟1月会更新EFI来适配MacOS12的
 -I’m a little busy lately, I will update EFI to adapt to MacOS12 in January at the latest

**Comment by mishailovic** [comment]
> > Will you update EFI for macOS Monterey or you're dropped the development?
> 
> 最近有点忙，最迟1月会更新EFI来适配MacOS12的 -I’m a little busy lately, I will update EFI to adapt to MacOS12 in January at the latest

Great 👍
