### ISSUE TITLE
Install using OpenCore files

### ISSUE THREAD

**Issue by joaovvrodrigues** [vicjl/Dell7567-OC#2]
Hello I found your proposal very interesting, but I have some doubts. I currently have this same machine, but with 8gb, running the Catalina version Olalira. I really wish I could switch, and I saw that in the guide you recommend switching from Clover to OC, I even tried, but I couldn't boot after. But my question is, I have a pendrive with Catalina's .app to perform the clean installation, I can't really use these files for a clean installation? Because I made the bootable pendrive and I was unable to complete the installation boot, It was stuck on the Apple symbol, certainly there was an error but I still don't know how to activate -v. Thanks for the excellent work, I will not give up trying to use your files!

**Comment by vicjl** [comment]
> Hello I found your proposal very interesting, but I have some doubts. I currently have this same machine, but with 8gb, running the Catalina version Olalira. I really wish I could switch, and I saw that in the guide you recommend switching from Clover to OC, I even tried, but I couldn't boot after. But my question is, I have a pendrive with Catalina's .app to perform the clean installation, I can't really use these files for a clean installation? Because I made the bootable pendrive and I was unable to complete the installation boot, It was stuck on the Apple symbol, certainly there was an error but I still don't know how to activate -v. Thanks for the excellent work, I will not give up trying to use your files!

首先你需要确保你已经解锁了CFG，我尝试了全新安装是可以的，目前缺少一些样本所以我不确定都可以全新安装，-v的快捷键是alt+v，（这是我的问题，下一个版本会变为win+v），你还需要确保你OC文件结构正确，Kexts文件夹中不能再有文件夹（有人因为这个问题出错）很抱歉因为一些词汇我无法翻译准确所以只能用中文回复你

**Comment by joaovvrodrigues** [comment]
is there any other tutorial for unlocking the CFG for me to install? I didn't understand it very well and my set_dump.app doesn't open on my current Hackintosh.

**Comment by joaovvrodrigues** [comment]
In fact I would like to know what the need to unlock CFG is. because I haven't seen it in other places ...Is there any way to install without it? If so, what will be the loss? For example internet will not work ... Among other things

**Comment by vicjl** [comment]
> In fact I would like to know what the need to unlock CFG is. because I haven't seen it in other places ...Is there any way to install without it? If so, what will be the loss? For example internet will not work ... Among other things

解锁CFG的目的是使用原生nvram和更好的电源管理，如果不解锁CFG，就需要使用模拟NVRAM，这有一篇详细教程https://hyejeong.cn/unlockbios     ，里面有相应的解释

**Comment by vicjl** [comment]
> is there any other tutorial for unlocking the CFG for me to install? I didn't understand it very well and my set_dump.app doesn't open on my current Hackintosh.

通常情况下你只需要这两步
从我们的modGRUBShell.efi(可以像添加Clover启动项一样将这个efi文件添加为启动项)启动；
进入之后输入setup_var_3 0x4DE，查看返回值是不是0x01

**Comment by joaovvrodrigues** [comment]
I am convinced that I will unlock my CFG, can I call you on Telegram just to be sure that I will make the correct steps? I can follow your tutorial, it seemed simple but as you say There may be a problem.

**Comment by joaovvrodrigues** [comment]
Hello, thank you very much for the answer! I managed to install it perfectly.But you are not recognizing my Ethernet cable, do you know what it could be? 

wi-fi also didn't work even configuring in Kext's config.plist, but if only the cable works, that's fine.  My network card is also it's WD1820.

**Comment by joaovvrodrigues** [comment]
In this latest release, I don't need to split between Intel and Broadcom anymore either? I had installed using the Intel version, since there is no longer this distinction I have to reinstall?

**Comment by vicjl** [comment]
> In this latest release, I don't need to split between Intel and Broadcom anymore either? I had installed using the Intel version, since there is no longer this distinction I have to reinstall?

不需要重新安装，只需替换文件即可，不区分的原因是我取消勾选了相关驱动，需要的话再次添加，博通需要勾选注释中bcrm开头的驱动。使用OpenCore Configurator会更方便。打开config.plist文件后，在Kernel处勾选

**Comment by vicjl** [comment]
> Hello, thank you very much for the answer! I managed to install it perfectly.But you are not recognizing my Ethernet cable, do you know what it could be?
> 
> wi-fi also didn't work even configuring in Kext's config.plist, but if only the cable works, that's fine. My network card is also it's WD1820.

以太网的话可能需要将Kexts中的RealtekRTL8111.kext替换为2.2.2版本，已有多人报告该问题，下个版本会修复

**Comment by joaovvrodrigues** [comment]
Thank you! You are awesome, tomorrow I will try. Because mine is WD1820, I don't use Broadcom, but Intel, right? So I need to configure I want to use Intel through OpenCore Config?

**Comment by vicjl** [comment]
> Thank you! You are awesome, tomorrow I will try. Because mine is WD1820, I don't use Broadcom, but Intel, right? So I need to configure I want to use Intel through OpenCore Config?

不好意思我以为你是dw1820a，（btw 我没有搜到有关WD1820的信息）如果是Intel的话勾选注释中包含Intel的几个Kexts，WIFI的SSID和密码可以在驱动中进行修改，也可以在对应的GUI（类原生的选择WIFI界面，就是HeliPort）中修改，不过GUI目前还有一点bug

**Comment by joaovvrodrigues** [comment]
Thanks for the help, I managed to install! The ethernet cable is working normally when updating Kext, everything is great! Fan control and intel monitor is normal, audio too, a question, What app are you using to monitor the temperature on your printscreens?

Bluetooth I managed to make it work by activating the Intel Bluetooth Kext, only the wifi that didn't work should have some relationship with my Network Card, but that's okay for now.

Thank you for your excellent work!

**Comment by vicjl** [comment]
> Thanks for the help, I managed to install! The ethernet cable is working normally when updating Kext, everything is great! Fan control and intel monitor is normal, audio too, a question, What app are you using to monitor the temperature on your printscreens?
> 
> Bluetooth I managed to make it work by activating the Intel Bluetooth Kext, only the wifi that didn't work should have some relationship with my Network Card, but that's okay for now.
> 
> Thank you for your excellent work!

截图中的是iStatistica Pro，也可以使用iStat Menus
