### ISSUE TITLE
Trackpad

### ISSUE THREAD

**Issue by th146o** [vicjl/Dell7567-OC#5]
Hello!

I performed the installation directly using opencore 0.6.0.
The trackpad is not 100% functional. The left button does not work right and I am also unable to configure the trackpad.
It always stays on that screen saying that no trackpad was found.
I tried to update all kexts and also opencore it to version 0.6.2, but I was not successful.
I would like you to help me, please.
If you need any more specific information, just tell me.

![IMG_1308](https://user-images.githubusercontent.com/24367807/95535060-70bb8480-09b5-11eb-8b10-65c5831c5264.JPEG)

**Comment by vicjl** [comment]
> Hello!
> 
> I performed the installation directly using opencore 0.6.0.
> The trackpad is not 100% functional. The left button does not work right and I am also unable to configure the trackpad.
> It always stays on that screen saying that no trackpad was found.
> I tried to update all kexts and also opencore it to version 0.6.2, but I was not successful.
> I would like you to help me, please.
> If you need any more specific information, just tell me.
> 
> ![IMG_1308](https://user-images.githubusercontent.com/24367807/95535060-70bb8480-09b5-11eb-8b10-65c5831c5264.JPEG)

你是直接使用了github最新的release还是自己有改动？是否使用了FakeSMC？如果是就换成VirtualSMC

**Comment by th146o** [comment]
I used the most recent version that you made available.
I'm using VirtualSMC.
I didn't make any changes to the files.
I had to use a USB mouse to install the Catalina system. Could this be the problem?

**Comment by vicjl** [comment]
> I used the most recent version that you made available.
> I'm using VirtualSMC.
> I didn't make any changes to the files.
> I had to use a USB mouse to install the Catalina system. Could this be the problem?

USB鼠标应该不会是问题，我在尝试定位问题，请等待几天后（预计时间在big sur出正式版后）的更新

**Comment by joaovvrodrigues** [comment]
I would like to make it clear that here I did not get this problem, using exactly the git files, in version 10.15.6. Everything is working perfectly.

**Comment by vicjl** [comment]
> Hello!
> 
> I performed the installation directly using opencore 0.6.0.
> The trackpad is not 100% functional. The left button does not work right and I am also unable to configure the trackpad.
> It always stays on that screen saying that no trackpad was found.
> I tried to update all kexts and also opencore it to version 0.6.2, but I was not successful.
> I would like you to help me, please.
> If you need any more specific information, just tell me.
> 
> ![IMG_1308](https://user-images.githubusercontent.com/24367807/95535060-70bb8480-09b5-11eb-8b10-65c5831c5264.JPEG)

尝试今天更新的新版本

**Comment by th146o** [comment]
你好！

我直接使用opencore 0.6.0执行安装。
触控板不是100％可用的。左按钮无法正常工作，我也无法配置触控板。
它始终停留在该屏幕上，表示未找到触控板。
我尝试将所有kexts更新，也将其opencore升级到0.6.3版，但未成功。
我想请你帮我。
如果您需要更多具体信息，请告诉我。

**Comment by vicjl** [comment]
> 你好！
> 
> 我直接使用opencore 0.6.0执行安装。
> 触控板不是100％可用的。左按钮无法正常工作，我也无法配置触控板。
> 它始终停留在该屏幕上，表示未找到触控板。
> 我尝试将所有kexts更新，也将其opencore升级到0.6.3版，但未成功。
> 我想请你帮我。
> 如果您需要更多具体信息，请告诉我。

你好，我明白你的意思，我的意思是说你可以尝试使用我今天发布的1.1.0-1115版本，看看是否可以解决问题
Hello, I understand what you mean, what I mean is that you can try the 1.1.0-1115 version I released today to see if it can solve the problem

**Comment by joaovvrodrigues** [comment]
@vicjl In order not to open another issue, check out the 'Kext' Realtek RTL8111, I had to downgrade the Ethernet cable to work here.
Another question, are you already using the BigSur version?

**Comment by vicjl** [comment]
> @vicjl In order not to open another issue, check out the 'Kext' Realtek RTL8111, I had to downgrade the Ethernet cable to work here.
> Another question, are you already using the BigSur version?

首先，关于Realtek RTL8111，确实有部分用户无法使用新版本，需要使用以前的旧版本，新版本在我这里是可以使用的，所以我更新了，我将会根据之后的反馈考虑使用旧版本驱动的。
其次，我确实使用了big sur版本，目前版本为11.0.1（20B29）
First, about Realtek rtl8111, it is true that some users can not use the new version and need to use the previous old version. The new version can be worked on my pc , so I updated it. I will consider using the old version based on the feedback later.Secondly, I did use the Big Sur version, which is currently 11.0.1 (20b29)

**Comment by vicjl** [comment]
> @vicjl In order not to open another issue, check out the 'Kext' Realtek RTL8111, I had to downgrade the Ethernet cable to work here.
> Another question, are you already using the BigSur version?

![Uploading IMG_20201116_011318.jpg…]()

**Comment by vicjl** [comment]
> @vicjl In order not to open another issue, check out the 'Kext' Realtek RTL8111, I had to downgrade the Ethernet cable to work here.
> Another question, are you already using the BigSur version?

![Uploading IMG_20201116_011318.jpg…]()

**Comment by vicjl** [comment]
> @vicjl In order not to open another issue, check out the 'Kext' Realtek RTL8111, I had to downgrade the Ethernet cable to work here.
> Another question, are you already using the BigSur version?

![about](https://user-images.githubusercontent.com/43945856/99191787-eb907000-27a9-11eb-8d81-934e068daf8b.jpg)

**Comment by vicjl** [comment]
> @vicjl In order not to open another issue, check out the 'Kext' Realtek RTL8111, I had to downgrade the Ethernet cable to work here.
> Another question, are you already using the BigSur version?

顺便一提，如果你是4K屏用户，我不建议升级Big Sur，因为需要修补edid，而且只能到4K@48Hz，需要等驱动更新，但是目前还没有好的解决方案，我的电脑同时安装了10.15.7和11.0，11.0只是好奇和测试目的
