### ISSUE TITLE
Blog Link

### ISSUE THREAD

**Issue by joaovvrodrigues** [vicjl/Dell7567-OC#6]
You said that updates are posted on your blog, could you let me know the link?
I'm using your git on my personal machine and I want to keep myself updated. Nice work, thank you!

**Comment by vicjl** [comment]
更新依旧会在github，不用担心，个人博客会放一些readme.md精简掉的内容，不会有OC更新，目前博客尚未搭建完成
The update will still be on github, don’t worry, the personal blog will put some content streamlined in readme.md, there will be no OC update, the blog has not been built yet.

**Comment by vicjl** [comment]
> You said that updates are posted on your blog, could you let me know the link?
> I'm using your git on my personal machine and I want to keep myself updated. Nice work, thank you!

更新依旧会在github，不用担心，个人博客会放一些readme.md精简掉的内容，不会有OC更新，目前博客尚未搭建完成
The update will still be on github, don’t worry, the personal blog will put some content streamlined in readme.md, there will be no OC update, the blog has not been built yet.
