### ISSUE TITLE
[Recent update comment] RealtekRTL8111.kext

### ISSUE THREAD

**Issue by joaovvrodrigues** [vicjl/Dell7567-OC#7]
I would like to leave this comment just to be aware, Not a serious problem.
Even with today's update I still had the same problems with RealtekRTL8111.kext, of not working with cable internet.

**So I returned RealtekRTL8111.kext to previous versions. And it worked normally.**
Will I always have to use an outdated version of this Kext?

**Thanks for the constant updates!**

**Comment by vicjl** [comment]
有很多人都有这样的问题(https://github.com/Mieze/RTL8111_driver_for_OS_X/issues?q=is%3Aissue+is%3Aclosed)  ，但在驱动作者Mieze的测试中似乎一切正常。有一条Issue提供的解决思路：手动配置硬件。我的笔记本使用2.4.0b6版本，千兆网络时正常，如果还是无法解决有线问题的话那目前只有两个方法：
1.在系统偏好设置→网络→高级→硬件处手动配置
2.使用旧版本
<img width="674" alt="20200119" src="https://user-images.githubusercontent.com/43945856/105047038-cfa89380-5aa4-11eb-96ec-b2280c159a9a.png">

**Comment by joaovvrodrigues** [comment]
It really seems that manually configuring works. Sorry and Thanks!
