### ISSUE TITLE
Graphic acceleration and spoofing

### ISSUE THREAD

**Issue by Mrsevic** [vicjl/Dell7567-OC#8]
Hi! Many thanks again for these files. Do you have some tutorial to follow on how to enable the gpu acceleration(at the moment being with the provided files my color depth is really low and chess app stutters occasionally).

Tutorial on spoofing would also be recommended.

Thanks

**Comment by vicjl** [comment]
你好，关于GPU加速，理论上是没问题的，你是否有能体现问题的截图或者视频？我确定一下问题

**Comment by Mrsevic** [comment]
你好，
我目前没有笔记本电脑，但基本上问题与那边的可视化问题相似：
https://www.tonymacx86.com/attachments/362626/
https://preview.redd.it/ohhyu77sr7i31.jpg?width=3024&format=pjpg&auto=webp&s=4a944a9de60eb728f81bed1cc8fef6e80d724a22

此外，系统在某些图形密集型操作（打开国际象棋应用程序移动几个数字，打开 iOS 模拟器）中似乎很缓慢。

亲切的问候，

斯特凡 

----------------------------------------------------------------------------------------------------------------------------------------
**ORIGINAL:**
Hi,
I do not have my laptop at me at the moment being but essentially the problem is similar as the one visualized over there:
https://www.tonymacx86.com/attachments/362626/
https://preview.redd.it/ohhyu77sr7i31.jpg?width=3024&format=pjpg&auto=webp&s=4a944a9de60eb728f81bed1cc8fef6e80d724a22

Also the system seem sluggish in certain graphical intensive operations(open the chess app move a couple of figures, open iOS simulator).

Kind regards,

Stefan

**Comment by vicjl** [comment]
你好，请告诉我你使用的release版本，系统版本，并请截图关于本机-系统报告-图形卡\显示器部分，如果Release不是最新，请尝试使用最新版1.3.0-0609 OC-A 0.7.0
